apiVersion: v1
kind: Pod
metadata:
  name: currency-exchange-pod
spec:
  containers:
    - image: eu.gcr.io/dvt-kube-app/currency-exchange-service
      name: currency-exchange-service
      ports:
        - containerPort: 8000
          protocol: TCP

